package gt.research.core.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import gt.research.core.db.Apk;
import gt.research.core.db.Intf;

import gt.research.core.db.ApkDao;
import gt.research.core.db.IntfDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig apkDaoConfig;
    private final DaoConfig intfDaoConfig;

    private final ApkDao apkDao;
    private final IntfDao intfDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        apkDaoConfig = daoConfigMap.get(ApkDao.class).clone();
        apkDaoConfig.initIdentityScope(type);

        intfDaoConfig = daoConfigMap.get(IntfDao.class).clone();
        intfDaoConfig.initIdentityScope(type);

        apkDao = new ApkDao(apkDaoConfig, this);
        intfDao = new IntfDao(intfDaoConfig, this);

        registerDao(Apk.class, apkDao);
        registerDao(Intf.class, intfDao);
    }
    
    public void clear() {
        apkDaoConfig.getIdentityScope().clear();
        intfDaoConfig.getIdentityScope().clear();
    }

    public ApkDao getApkDao() {
        return apkDao;
    }

    public IntfDao getIntfDao() {
        return intfDao;
    }

}
