package gt.research.dc.core.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APK".
 */
public class Apk {

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String version;
    /** Not-null value. */
    private String url;

    public Apk() {
    }

    public Apk(String id) {
        this.id = id;
    }

    public Apk(String id, String version, String url) {
        this.id = id;
        this.version = version;
        this.url = url;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVersion() {
        return version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVersion(String version) {
        this.version = version;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

}
