package gt.research.dc.core.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import gt.research.dc.core.db.Comp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMP".
*/
public class CompDao extends AbstractDao<Comp, String> {

    public static final String TABLENAME = "COMP";

    /**
     * Properties of entity Comp.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Comp = new Property(0, String.class, "comp", true, "COMP");
        public final static Property Apk = new Property(1, String.class, "apk", false, "APK");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
    };


    public CompDao(DaoConfig config) {
        super(config);
    }
    
    public CompDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMP\" (" + //
                "\"COMP\" TEXT PRIMARY KEY NOT NULL ," + // 0: comp
                "\"APK\" TEXT NOT NULL ," + // 1: apk
                "\"TYPE\" TEXT NOT NULL );"); // 2: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Comp entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getComp());
        stmt.bindString(2, entity.getApk());
        stmt.bindString(3, entity.getType());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Comp readEntity(Cursor cursor, int offset) {
        Comp entity = new Comp( //
            cursor.getString(offset + 0), // comp
            cursor.getString(offset + 1), // apk
            cursor.getString(offset + 2) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Comp entity, int offset) {
        entity.setComp(cursor.getString(offset + 0));
        entity.setApk(cursor.getString(offset + 1));
        entity.setType(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Comp entity, long rowId) {
        return entity.getComp();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Comp entity) {
        if(entity != null) {
            return entity.getComp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
