package gt.research.dc.core.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import gt.research.dc.core.db.Apk;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APK".
*/
public class ApkDao extends AbstractDao<Apk, String> {

    public static final String TABLENAME = "APK";

    /**
     * Properties of entity Apk.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Apk = new Property(0, String.class, "apk", true, "APK");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property PkgName = new Property(2, String.class, "pkgName", false, "PKG_NAME");
        public final static Property Timestamp = new Property(3, long.class, "timestamp", false, "TIMESTAMP");
    };


    public ApkDao(DaoConfig config) {
        super(config);
    }
    
    public ApkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APK\" (" + //
                "\"APK\" TEXT PRIMARY KEY NOT NULL ," + // 0: apk
                "\"URL\" TEXT NOT NULL ," + // 1: url
                "\"PKG_NAME\" TEXT," + // 2: pkgName
                "\"TIMESTAMP\" INTEGER NOT NULL );"); // 3: timestamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Apk entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getApk());
        stmt.bindString(2, entity.getUrl());
 
        String pkgName = entity.getPkgName();
        if (pkgName != null) {
            stmt.bindString(3, pkgName);
        }
        stmt.bindLong(4, entity.getTimestamp());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Apk readEntity(Cursor cursor, int offset) {
        Apk entity = new Apk( //
            cursor.getString(offset + 0), // apk
            cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pkgName
            cursor.getLong(offset + 3) // timestamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Apk entity, int offset) {
        entity.setApk(cursor.getString(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
        entity.setPkgName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTimestamp(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Apk entity, long rowId) {
        return entity.getApk();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Apk entity) {
        if(entity != null) {
            return entity.getApk();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
